# Generated by Django 4.2.16 on 2024-12-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=255)),
                ('discription_tour', models.TextField()),
                ('price_tour', models.IntegerField()),
                ('departure', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('date_departure', models.DateField()),
                ('date_return', models.DateField()),
                ('operator_tour', models.CharField(max_length=255)),
                ('places_tour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255)),
                ('email_user', models.EmailField(max_length=254, unique=True)),
                ('role_user', models.CharField(max_length=50)),
                ('password_user', models.CharField(max_length=255)),
                ('number_user', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stock', models.CharField(max_length=255)),
                ('stock_value', models.IntegerField()),
                ('status_stock', models.BooleanField()),
                ('id_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField()),
                ('id_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField()),
                ('status_pay', models.BooleanField()),
                ('payment_method', models.CharField(max_length=50)),
                ('id_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user')),
            ],
        ),
    ]
