# Generated by Django 4.2.16 on 2024-12-16 12:08

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price_tour',
            field=models.IntegerField(validators=[travel.models.validate_positive]),
        ),
    ]
