# Generated by Django 4.2.16 on 2025-01-18 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_pay',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
    ]
