# Generated by Django 4.2.16 on 2024-12-16 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import travel.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_alter_tour_price_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(max_length=50, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_pay',
            field=models.BooleanField(verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name_stock',
            field=models.CharField(max_length=255, verbose_name='Название акции'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status_stock',
            field=models.BooleanField(verbose_name='Статус акции'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_value',
            field=models.IntegerField(validators=[travel.models.validate_positive], verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_departure',
            field=models.DateField(verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_return',
            field=models.DateField(verbose_name='Дата возвращения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure',
            field=models.CharField(max_length=255, verbose_name='Место отправления'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='Место назначения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='discription_tour',
            field=models.TextField(verbose_name='Описание тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name_tour',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='operator_tour',
            field=models.CharField(max_length=255, verbose_name='Туроператор'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='places_tour',
            field=models.IntegerField(validators=[travel.models.validate_positive], verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price_tour',
            field=models.IntegerField(validators=[travel.models.validate_positive], verbose_name='Цена тура'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_user',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_user',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_user',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_user',
            field=models.CharField(max_length=255, verbose_name='Пароль пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_user',
            field=models.CharField(max_length=50, verbose_name='Роль пользователя'),
        ),
        migrations.CreateModel(
            name='HistoricalTour',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_tour', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('discription_tour', models.TextField(verbose_name='Описание тура')),
                ('price_tour', models.IntegerField(validators=[travel.models.validate_positive], verbose_name='Цена тура')),
                ('departure', models.CharField(max_length=255, verbose_name='Место отправления')),
                ('destination', models.CharField(max_length=255, verbose_name='Место назначения')),
                ('date_departure', models.DateField(verbose_name='Дата отправления')),
                ('date_return', models.DateField(verbose_name='Дата возвращения')),
                ('operator_tour', models.CharField(max_length=255, verbose_name='Туроператор')),
                ('places_tour', models.IntegerField(validators=[travel.models.validate_positive], verbose_name='Количество мест')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical tour',
                'verbose_name_plural': 'historical tours',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
