# Generated by Django 4.2.16 on 2025-01-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_favorite_id_tour_alter_favorite_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltour',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaltour',
            name='name_tour',
            field=models.CharField(max_length=255, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name_tour',
            field=models.CharField(max_length=255, verbose_name='Название тура'),
        ),
    ]
