# Generated by Django 4.2.16 on 2025-01-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_historicaltour_url_description_reservation_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltour',
            name='url_description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='url_description',
        ),
        migrations.AddField(
            model_name='historicaltour',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видеообзор'),
        ),
        migrations.AddField(
            model_name='tour',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на видеообзор'),
        ),
    ]
