# Generated by Django 4.2.16 on 2025-01-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_historicaltour_is_hot_tour_is_hot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltour',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
