# Generated by Django 4.2.16 on 2025-01-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_historicaltour_image_tour_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['date_departure']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='travel.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Банковская карта'), ('CASH', 'Наличные'), ('ONLINE', 'Онлайн оплата(СБП)')], max_length=50, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='travel.tour', verbose_name='Тур'),
        ),
    ]
