# Generated by Django 4.2.16 on 2025-01-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_favorite_options_alter_historicaltour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(max_length=500),
        ),
    ]
